# Generated by Django 5.0.2 on 2024-03-20 21:21

import django.db.models.deletion
from django.conf import settings
# Generated by Django 4.1.7 on 2024-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_pr', models.TextField(blank=True)),
                ('squat_pr', models.TextField(blank=True)),
                ('deadlift_pr', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ])
    ]
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PRModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
