# Generated by Django 4.1.7 on 2024-03-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_workoutroutine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutroutine",
            old_name="friday_workout",
            new_name="friday",
        ),
        migrations.RenameField(
            model_name="workoutroutine",
            old_name="monday_workout",
            new_name="monday",
        ),
        migrations.RenameField(
            model_name="workoutroutine",
            old_name="saturday_workout",
            new_name="saturday",
        ),
        migrations.RenameField(
            model_name="workoutroutine",
            old_name="sunday_workout",
            new_name="sunday",
        ),
        migrations.RenameField(
            model_name="workoutroutine",
            old_name="thursday_workout",
            new_name="thursday",
        ),
        migrations.RenameField(
            model_name="workoutroutine",
            old_name="tuesday_workout",
            new_name="tuesday",
        ),
        migrations.RenameField(
            model_name="workoutroutine",
            old_name="wednesday_workout",
            new_name="wednesday",
        ),
    ]
